services:
  db:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_ROOT_USERNAME: root
      MYSQL_DATABASE: vetmasters
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  backend:
    build: .
    container_name: api
    ports:
      - '8080:8080'
    depends_on:
      - db
volumes:
  my-db:
